version: '3'
services:

  aggregator:
    container_name: hedger-aggregator
    build:
      context: ../
      dockerfile: src/HedgeR.Aggregator/Dockerfile
    restart: unless-stopped
    ports:
      - 5010:80
    networks:
      - hedger

  spot:
    container_name: hedger-spot
    build:
      context: ../
      dockerfile:  src/HedgeR.Feeds/Spot/Dockerfile
    restart: unless-stopped
    ports:
      - 5020:80
    networks:
      - hedger

  fees:
    container_name: hedger-fees
    build:
      context: ../
      dockerfile: src/HedgeR.Feeds/Fees/Dockerfile
    restart: unless-stopped
    ports:
      - 5030:80
    networks:
      - hedger

  spread:
    container_name: hedger-spread
    build:
      context: ../
      dockerfile: src/HedgeR.Feeds/Spread/Dockerfile
    restart: unless-stopped
    ports:
      - 5040:80
    networks:
      - hedger
    depends_on:
       - hedger-aggregator

  pricer:
    container_name: hedger-pricer
    build:
      context: ../
      dockerfile:  src/HedgeR.Pricer/Dockerfile
    restart: unless-stopped
    ports:
      - 5050:80
    networks:
      - hedger
      
networks:
  hedger:
    name: hedger
    #external: true